- name: "Install KVM"
  apt:
    name:
      - qemu-system
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system
      - bridge-utils 
      - virtinst
      - virt-manager
    state: present
    update_cache: true
  become: true
